# Generated by Django 3.2.5 on 2023-09-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTicket',
        ),
    ]
