# Generated by Django 3.2.5 on 2023-08-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('Responsibility', models.CharField(blank=True, max_length=100, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('PasswordEmail', models.CharField(blank=True, max_length=256, null=True)),
                ('Tel', models.CharField(blank=True, max_length=50, null=True)),
                ('ClientID', models.IntegerField(blank=True, null=True)),
                ('UserName', models.CharField(blank=True, max_length=100, null=True)),
                ('PASSWORD', models.CharField(blank=True, max_length=100, null=True)),
                ('Skype', models.CharField(blank=True, max_length=100, null=True)),
                ('IsActive', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('NewID', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
