# Generated by Django 3.2.5 on 2023-08-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_build_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FacID',
        ),
    ]
