# Generated by Django 3.2.5 on 2023-09-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_userticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_main', models.IntegerField(blank=True, null=True)),
                ('Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
                ('WebServiceURL', models.CharField(blank=True, max_length=255, null=True)),
                ('ActiveYN', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
