# Generated by Django 3.2.5 on 2023-09-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/logo'),
        ),
    ]
