//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Features_Ref
    {
        public int RowID { get; set; }
        public string FeatureCode_Source { get; set; }
        public string FeatureCode_Ref { get; set; }
        public string RefText { get; set; }
    }
}
