//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instance
    {
        public System.Guid InstanceID { get; set; }
        public string ClientName { get; set; }
        public string InstanceName { get; set; }
        public string InstanceType { get; set; }
        public string WebService { get; set; }
    }
}
