//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_CongViec
    {
        public System.Guid Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> MucDo { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
