//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Features
    {
        public int RowID { get; set; }
        public string Prefix { get; set; }
        public string Number { get; set; }
        public string Code { get; set; }
        public string Module { get; set; }
        public string Menu { get; set; }
        public string SubMenu { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
