//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_QLDA_DuAn
    {
        public int MaDA { get; set; }
        public string TenDA { get; set; }
        public string MaKV { get; set; }
        public string MaNhomKH { get; set; }
        public string MaLoaiCS { get; set; }
        public Nullable<int> MaLoaiDN { get; set; }
        public Nullable<int> MaLoaiNganh { get; set; }
        public Nullable<int> SoLuongKhoaPhong { get; set; }
        public Nullable<int> SoLuotKham { get; set; }
        public Nullable<int> SoLuotGiuong { get; set; }
        public Nullable<int> MaHangBV { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string PMDangSD { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public Nullable<int> MaNhuCau { get; set; }
        public Nullable<int> MaMucDoUuTien { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public string MaLoaiDoanhThu { get; set; }
        public string GhiChu { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
    }
}
