//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_QLDA_CongNo
    {
        public System.Guid MaCongNo { get; set; }
        public Nullable<int> MaDA { get; set; }
        public Nullable<System.Guid> ContractID { get; set; }
        public Nullable<System.Guid> MaHSTT { get; set; }
        public Nullable<decimal> SoTienThu { get; set; }
        public Nullable<decimal> SoTienDaThu { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> ChoTreTT { get; set; }
        public Nullable<int> MaSoLanTre { get; set; }
        public Nullable<System.DateTime> NgayNhacNo { get; set; }
    }
}
