//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_QLDA_NhanSu
    {
        public System.Guid ID { get; set; }
        public Nullable<int> MaDA { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MaBoPhan { get; set; }
        public string MaCV { get; set; }
        public string MaGD { get; set; }
        public string GhiChu { get; set; }
    }
}
