//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_QLDA_FileUpload
    {
        public int Seq { get; set; }
        public Nullable<int> MaDA { get; set; }
        public string FileName { get; set; }
        public string FileData { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> CreateBy { get; set; }
    }
}
