//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_QLDA_HoSoThanhToan
    {
        public System.Guid MaHSTT { get; set; }
        public Nullable<int> MaDA { get; set; }
        public Nullable<System.Guid> ContractID { get; set; }
        public string SoHSTT { get; set; }
        public string NoiDungTT { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayGuiHoSo { get; set; }
        public Nullable<System.DateTime> NgayKHNhanHS { get; set; }
        public string GhiChu { get; set; }
    }
}
