//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_QLDA_ThongTinLHKH
    {
        public System.Guid MaLH { get; set; }
        public Nullable<int> MaDA { get; set; }
        public string HoTen { get; set; }
        public string MaChucVu { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string SDT1 { get; set; }
        public string SDT2 { get; set; }
        public string GhiChu { get; set; }
    }
}
