//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_QLDA_LichSuSale
    {
        public System.Guid SaleHistoryID { get; set; }
        public Nullable<int> MaDA { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGianSale { get; set; }
        public string MucDich { get; set; }
        public string KetQua { get; set; }
        public string KhoKhan { get; set; }
        public string PhuongAn { get; set; }
        public string YKienCapTren { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
