//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_ReportInfo
    {
        public System.Guid ReportID { get; set; }
        public int ID { get; set; }
        public string OutputType { get; set; }
        public string Orientation { get; set; }
        public string FontName { get; set; }
        public string HeaderFontSize { get; set; }
        public string BodyFontSize { get; set; }
        public string FooterFontSize { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> Report_ID { get; set; }
        public string ReportName { get; set; }
        public string DEV { get; set; }
        public Nullable<bool> IsOnScreen { get; set; }
        public string DataProc { get; set; }
        public string ProgID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
