//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_TicketFuture
    {
        public long TicketID { get; set; }
        public int TeamID { get; set; }
        public int WeekID { get; set; }
        public Nullable<int> PrimaryDev { get; set; }
        public Nullable<int> ActualDev { get; set; }
        public Nullable<int> PrimaryQC { get; set; }
        public Nullable<int> ActualQC { get; set; }
        public Nullable<decimal> EstDEV { get; set; }
        public Nullable<decimal> EstTO { get; set; }
        public Nullable<decimal> EstQC { get; set; }
        public Nullable<decimal> HourInWeek { get; set; }
        public Nullable<System.DateTime> DeadlineCR { get; set; }
        public Nullable<System.DateTime> DeadlineTO { get; set; }
        public Nullable<System.DateTime> DeadlineQC { get; set; }
        public Nullable<System.DateTime> NgayGiaoQC { get; set; }
        public string DoOrNot { get; set; }
        public string Tuan { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
