//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules_Users
    {
        public int RowID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Module { get; set; }
        public Nullable<bool> ActiveYN { get; set; }
    }
}
