//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QAOrgDBContext : DbContext
    {
        public QAOrgDBContext()
            : base("name=QAOrgDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Builds> Builds { get; set; }
        public virtual DbSet<BuildTickets> BuildTickets { get; set; }
        public virtual DbSet<Client_Participants> Client_Participants { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<DanhSachPhanHeTamAnh> DanhSachPhanHeTamAnh { get; set; }
        public virtual DbSet<deleted_Mail> deleted_Mail { get; set; }
        public virtual DbSet<deleted_MailFiles> deleted_MailFiles { get; set; }
        public virtual DbSet<deleted_MailSender> deleted_MailSender { get; set; }
        public virtual DbSet<Features_Ref> Features_Ref { get; set; }
        public virtual DbSet<Installer> Installer { get; set; }
        public virtual DbSet<Instance> Instance { get; set; }
        public virtual DbSet<L_Attachment> L_Attachment { get; set; }
        public virtual DbSet<L_CongViec> L_CongViec { get; set; }
        public virtual DbSet<L_Features> L_Features { get; set; }
        public virtual DbSet<L_Lookup> L_Lookup { get; set; }
        public virtual DbSet<L_MucDo> L_MucDo { get; set; }
        public virtual DbSet<L_Position> L_Position { get; set; }
        public virtual DbSet<L_PrintLocation> L_PrintLocation { get; set; }
        public virtual DbSet<L_QLDA_BoPhan> L_QLDA_BoPhan { get; set; }
        public virtual DbSet<L_QLDA_CongNo> L_QLDA_CongNo { get; set; }
        public virtual DbSet<L_QLDA_ChucVu> L_QLDA_ChucVu { get; set; }
        public virtual DbSet<L_QLDA_ChucVuKH> L_QLDA_ChucVuKH { get; set; }
        public virtual DbSet<L_QLDA_DuAn> L_QLDA_DuAn { get; set; }
        public virtual DbSet<L_QLDA_FileUpload> L_QLDA_FileUpload { get; set; }
        public virtual DbSet<L_QLDA_GDDA> L_QLDA_GDDA { get; set; }
        public virtual DbSet<L_QLDA_GiaiDoan> L_QLDA_GiaiDoan { get; set; }
        public virtual DbSet<L_QLDA_HangBenhVien> L_QLDA_HangBenhVien { get; set; }
        public virtual DbSet<L_QLDA_HopDong> L_QLDA_HopDong { get; set; }
        public virtual DbSet<L_QLDA_HoSoThanhToan> L_QLDA_HoSoThanhToan { get; set; }
        public virtual DbSet<L_QLDA_KhachHang> L_QLDA_KhachHang { get; set; }
        public virtual DbSet<L_QLDA_KhuVuc> L_QLDA_KhuVuc { get; set; }
        public virtual DbSet<L_QLDA_LichSuSale> L_QLDA_LichSuSale { get; set; }
        public virtual DbSet<L_QLDA_LoaiCoSo> L_QLDA_LoaiCoSo { get; set; }
        public virtual DbSet<L_QLDA_LoaiDoanhThu> L_QLDA_LoaiDoanhThu { get; set; }
        public virtual DbSet<L_QLDA_LoaiHinhDoanhNghiep> L_QLDA_LoaiHinhDoanhNghiep { get; set; }
        public virtual DbSet<L_QLDA_LoaiHopDong> L_QLDA_LoaiHopDong { get; set; }
        public virtual DbSet<L_QLDA_LoaiNganh> L_QLDA_LoaiNganh { get; set; }
        public virtual DbSet<L_QLDA_LoaiTien> L_QLDA_LoaiTien { get; set; }
        public virtual DbSet<L_QLDA_MucDoUuTien> L_QLDA_MucDoUuTien { get; set; }
        public virtual DbSet<L_QLDA_NhanSu> L_QLDA_NhanSu { get; set; }
        public virtual DbSet<L_QLDA_NhomKH> L_QLDA_NhomKH { get; set; }
        public virtual DbSet<L_QLDA_NhuCau> L_QLDA_NhuCau { get; set; }
        public virtual DbSet<L_QLDA_SoLanTre> L_QLDA_SoLanTre { get; set; }
        public virtual DbSet<L_QLDA_ThoiHan> L_QLDA_ThoiHan { get; set; }
        public virtual DbSet<L_QLDA_ThongTinLHKH> L_QLDA_ThongTinLHKH { get; set; }
        public virtual DbSet<L_QLDA_TrangThai> L_QLDA_TrangThai { get; set; }
        public virtual DbSet<L_ReportCollumsDetails> L_ReportCollumsDetails { get; set; }
        public virtual DbSet<L_ReportDetail> L_ReportDetail { get; set; }
        public virtual DbSet<L_ReportInfo> L_ReportInfo { get; set; }
        public virtual DbSet<L_ReportParam> L_ReportParam { get; set; }
        public virtual DbSet<L_Reports> L_Reports { get; set; }
        public virtual DbSet<L_ReportsSign> L_ReportsSign { get; set; }
        public virtual DbSet<L_Tags> L_Tags { get; set; }
        public virtual DbSet<L_TeamMembers> L_TeamMembers { get; set; }
        public virtual DbSet<L_Teams> L_Teams { get; set; }
        public virtual DbSet<L_TicketErrorProtocol> L_TicketErrorProtocol { get; set; }
        public virtual DbSet<L_TicketErrors> L_TicketErrors { get; set; }
        public virtual DbSet<L_TinhTrang> L_TinhTrang { get; set; }
        public virtual DbSet<MailHeader> MailHeader { get; set; }
        public virtual DbSet<MemoTemplates> MemoTemplates { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Modules_Users> Modules_Users { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ProjectUsers> ProjectUsers { get; set; }
        public virtual DbSet<RequirementOriginal> RequirementOriginal { get; set; }
        public virtual DbSet<SUP_Menu> SUP_Menu { get; set; }
        public virtual DbSet<SUP_Requirement> SUP_Requirement { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TA_MoiTruongDay> TA_MoiTruongDay { get; set; }
        public virtual DbSet<TA_TicketXacNhanDayMoiTruong> TA_TicketXacNhanDayMoiTruong { get; set; }
        public virtual DbSet<TamAnhHospitalRequest> TamAnhHospitalRequest { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Ticket_Estimations_Detail> Ticket_Estimations_Detail { get; set; }
        public virtual DbSet<Ticket_InWeek> Ticket_InWeek { get; set; }
        public virtual DbSet<Ticket_Log_Bugs> Ticket_Log_Bugs { get; set; }
        public virtual DbSet<Ticket_Log_Bugs_Files> Ticket_Log_Bugs_Files { get; set; }
        public virtual DbSet<Ticket_Menu> Ticket_Menu { get; set; }
        public virtual DbSet<Ticket_QC_Estimation_Detail> Ticket_QC_Estimation_Detail { get; set; }
        public virtual DbSet<Ticket_ReleaseNote> Ticket_ReleaseNote { get; set; }
        public virtual DbSet<Ticket_RequirementOriginal> Ticket_RequirementOriginal { get; set; }
        public virtual DbSet<Ticket_Tuan_PreSource> Ticket_Tuan_PreSource { get; set; }
        public virtual DbSet<Ticket_Week> Ticket_Week { get; set; }
        public virtual DbSet<TicketClients> TicketClients { get; set; }
        public virtual DbSet<TicketCompleted> TicketCompleted { get; set; }
        public virtual DbSet<TicketDLLs> TicketDLLs { get; set; }
        public virtual DbSet<TicketEmails> TicketEmails { get; set; }
        public virtual DbSet<TicketErrors> TicketErrors { get; set; }
        public virtual DbSet<TicketEstimations> TicketEstimations { get; set; }
        public virtual DbSet<TicketFeature> TicketFeature { get; set; }
        public virtual DbSet<TicketFeature_Log> TicketFeature_Log { get; set; }
        public virtual DbSet<TicketFiles> TicketFiles { get; set; }
        public virtual DbSet<TicketFollow> TicketFollow { get; set; }
        public virtual DbSet<TicketHistory> TicketHistory { get; set; }
        public virtual DbSet<TicketHistoryLog> TicketHistoryLog { get; set; }
        public virtual DbSet<TicketNotes> TicketNotes { get; set; }
        public virtual DbSet<TicketReview> TicketReview { get; set; }
        public virtual DbSet<TicketSVN_Link> TicketSVN_Link { get; set; }
        public virtual DbSet<TicketTags> TicketTags { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Installer_History> Installer_History { get; set; }
        public virtual DbSet<L_DLLs> L_DLLs { get; set; }
        public virtual DbSet<L_TicketFuture> L_TicketFuture { get; set; }
        public virtual DbSet<ScriptsDeploy> ScriptsDeploy { get; set; }
        public virtual DbSet<TicketNoWeek> TicketNoWeek { get; set; }
    }
}
