//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHistory
    {
        public long Seq { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public int TicketID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<int> AssignedFrom { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string FromStatus { get; set; }
        public string ToStatus { get; set; }
        public bool Seen { get; set; }
        public string FromPriority { get; set; }
        public string ToPriority { get; set; }
    }
}
