//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets_ClientView
    {
        public string Number { get; set; }
        public string Module { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Severity { get; set; }
        public int Ticket { get; set; }
        public string BuildName { get; set; }
    }
}
