//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Tuan_PreSource
    {
        public int TicketID { get; set; }
        public int TuanID { get; set; }
        public string Note { get; set; }
        public string UuTien { get; set; }
        public Nullable<System.DateTime> DeadlineCR { get; set; }
        public string Team { get; set; }
    }
}
