//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketFeature_Log
    {
        public long HistorySeq { get; set; }
        public Nullable<int> Seq { get; set; }
        public int TicketID { get; set; }
        public string FeatureCode { get; set; }
        public Nullable<bool> DeleteYN { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
