//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketEstimations
    {
        public int TicketID { get; set; }
        public string BA { get; set; }
        public string DesignScreen { get; set; }
        public string LogicScreen { get; set; }
        public string SPScreen { get; set; }
        public string DesignReport { get; set; }
        public string SPReport { get; set; }
        public string DEV { get; set; }
        public string QC { get; set; }
        public string DEV_Real { get; set; }
        public string QC_Real { get; set; }
        public string BA_Real { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
