# Generated by Django 3.2.5 on 2023-09-07 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20230906_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='MapUserTicket',
        ),
        migrations.AddField(
            model_name='customuser',
            name='map_user_ticket',
            field=models.CharField(choices=[], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
