# Generated by Django 3.2.5 on 2023-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20230907_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='map_user_ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
