# Generated by Django 3.2.5 on 2023-09-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_customuser_map_user_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='map_user_ticket',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
