# Generated by Django 4.2.1 on 2023-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('BuildName', models.CharField(max_length=100)),
                ('BuildStatus', models.CharField(max_length=100)),
                ('BuildDeadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketID', models.IntegerField()),
                ('Priority', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('DueDate', models.DateTimeField(null=True)),
                ('AssignedTo', models.IntegerField(null=True)),
                ('Title', models.CharField(blank=True, max_length=1000, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=300, null=True)),
                ('MODULE', models.CharField(blank=True, max_length=300, null=True)),
                ('PrimaryDEV', models.IntegerField(blank=True, null=True)),
                ('PrimaryQC', models.IntegerField(blank=True, null=True)),
                ('PrimaryBA', models.IntegerField(blank=True, null=True)),
                ('TicketOwner', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
