# Generated by Django 3.2.5 on 2023-08-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
