# Generated by Django 4.2.1 on 2023-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketID', models.IntegerField()),
                ('Priority', models.CharField(blank=True, max_length=50)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('DueDate', models.DateTimeField()),
                ('AssignedTo', models.IntegerField()),
                ('Title', models.CharField(blank=True, max_length=1000)),
                ('Description', models.CharField(blank=True, max_length=3000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('Category', models.CharField(blank=True, max_length=300)),
                ('MODULE', models.CharField(blank=True, max_length=300)),
                ('PrimaryDEV', models.IntegerField()),
                ('PrimaryQC', models.IntegerField()),
                ('PrimaryBA', models.IntegerField()),
                ('TicketOwner', models.IntegerField()),
            ],
        ),
    ]
