# Generated by Django 3.2.5 on 2023-08-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0003_auto_20230830_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
