# Generated by Django 3.2.5 on 2023-08-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0004_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Build',
        ),
        migrations.DeleteModel(
            name='Build',
        ),
    ]
